# Generated by Django 2.2.5 on 2021-12-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20211229_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='check_out',
            field=models.TimeField(),
        ),
    ]
