# Generated by Django 2.2.5 on 2021-12-30 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_auto_20211230_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conservation',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='conservation', to=settings.AUTH_USER_MODEL),
        ),
    ]
